# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QGroupBox,
    QHeaderView, QLabel, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTableView, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(2080, 1746)
        self.actionCapture_img_png = QAction(MainWindow)
        self.actionCapture_img_png.setObjectName(u"actionCapture_img_png")
        self.actionYOLOv8n_pose = QAction(MainWindow)
        self.actionYOLOv8n_pose.setObjectName(u"actionYOLOv8n_pose")
        self.actionYOLO = QAction(MainWindow)
        self.actionYOLO.setObjectName(u"actionYOLO")
        self.actionYOLOv2 = QAction(MainWindow)
        self.actionYOLOv2.setObjectName(u"actionYOLOv2")
        self.actionYOLOv3 = QAction(MainWindow)
        self.actionYOLOv3.setObjectName(u"actionYOLOv3")
        self.actionYOLOv4 = QAction(MainWindow)
        self.actionYOLOv4.setObjectName(u"actionYOLOv4")
        self.actionYOLOv8x_pose = QAction(MainWindow)
        self.actionYOLOv8x_pose.setObjectName(u"actionYOLOv8x_pose")
        self.actionOpen_operating_scenario = QAction(MainWindow)
        self.actionOpen_operating_scenario.setObjectName(u"actionOpen_operating_scenario")
        self.actionLoad_sound_files = QAction(MainWindow)
        self.actionLoad_sound_files.setObjectName(u"actionLoad_sound_files")
        self.actionShow_Keypoints = QAction(MainWindow)
        self.actionShow_Keypoints.setObjectName(u"actionShow_Keypoints")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.action_capture_after_30s = QAction(MainWindow)
        self.action_capture_after_30s.setObjectName(u"action_capture_after_30s")
        self.actionconnect_All = QAction(MainWindow)
        self.actionconnect_All.setObjectName(u"actionconnect_All")
        self.actionCapture_Image_with_Keypoints_png = QAction(MainWindow)
        self.actionCapture_Image_with_Keypoints_png.setObjectName(u"actionCapture_Image_with_Keypoints_png")
        self.action_capture_after_20s = QAction(MainWindow)
        self.action_capture_after_20s.setObjectName(u"action_capture_after_20s")
        self.action_capture_after_10s = QAction(MainWindow)
        self.action_capture_after_10s.setObjectName(u"action_capture_after_10s")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.window_camera_2 = QLabel(self.centralwidget)
        self.window_camera_2.setObjectName(u"window_camera_2")
        self.window_camera_2.setGeometry(QRect(660, 10, 640, 360))
        self.window_camera_2.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.window_camera_2.setAlignment(Qt.AlignCenter)
        self.window_camera_1 = QLabel(self.centralwidget)
        self.window_camera_1.setObjectName(u"window_camera_1")
        self.window_camera_1.setGeometry(QRect(10, 10, 640, 360))
        self.window_camera_1.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.window_camera_1.setAlignment(Qt.AlignCenter)
        self.window_camera_4 = QLabel(self.centralwidget)
        self.window_camera_4.setObjectName(u"window_camera_4")
        self.window_camera_4.setGeometry(QRect(660, 380, 640, 360))
        self.window_camera_4.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.window_camera_4.setAlignment(Qt.AlignCenter)
        self.window_camera_3 = QLabel(self.centralwidget)
        self.window_camera_3.setObjectName(u"window_camera_3")
        self.window_camera_3.setGeometry(QRect(10, 380, 640, 360))
        self.window_camera_3.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.window_camera_3.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 750, 311, 71))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 20, 101, 16))
        self.progress_gpu_usage_2 = QProgressBar(self.groupBox)
        self.progress_gpu_usage_2.setObjectName(u"progress_gpu_usage_2")
        self.progress_gpu_usage_2.setGeometry(QRect(10, 40, 141, 23))
        self.progress_gpu_usage_2.setValue(0)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(160, 20, 131, 16))
        self.progress_gpu_mem_usage_2 = QProgressBar(self.groupBox)
        self.progress_gpu_mem_usage_2.setObjectName(u"progress_gpu_mem_usage_2")
        self.progress_gpu_mem_usage_2.setGeometry(QRect(160, 40, 141, 23))
        self.progress_gpu_mem_usage_2.setValue(0)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(1650, 50, 321, 211))
        self.label_ip = QLabel(self.groupBox_2)
        self.label_ip.setObjectName(u"label_ip")
        self.label_ip.setGeometry(QRect(10, 30, 121, 20))
        self.label_ip.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_name = QLabel(self.groupBox_2)
        self.label_name.setObjectName(u"label_name")
        self.label_name.setGeometry(QRect(10, 60, 121, 20))
        self.label_name.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_battery_level = QLabel(self.groupBox_2)
        self.label_battery_level.setObjectName(u"label_battery_level")
        self.label_battery_level.setGeometry(QRect(10, 90, 121, 20))
        self.label_battery_level.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_free_storage = QLabel(self.groupBox_2)
        self.label_free_storage.setObjectName(u"label_free_storage")
        self.label_free_storage.setGeometry(QRect(10, 150, 121, 20))
        self.label_free_storage.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_battery_state = QLabel(self.groupBox_2)
        self.label_battery_state.setObjectName(u"label_battery_state")
        self.label_battery_state.setGeometry(QRect(10, 120, 121, 20))
        self.label_battery_state.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_storage_level = QLabel(self.groupBox_2)
        self.label_storage_level.setObjectName(u"label_storage_level")
        self.label_storage_level.setGeometry(QRect(10, 180, 121, 20))
        self.label_storage_level.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_ip_text = QLabel(self.groupBox_2)
        self.label_ip_text.setObjectName(u"label_ip_text")
        self.label_ip_text.setGeometry(QRect(140, 32, 170, 16))
        self.label_name_text = QLabel(self.groupBox_2)
        self.label_name_text.setObjectName(u"label_name_text")
        self.label_name_text.setGeometry(QRect(140, 62, 170, 16))
        self.label_battery_level_text = QLabel(self.groupBox_2)
        self.label_battery_level_text.setObjectName(u"label_battery_level_text")
        self.label_battery_level_text.setGeometry(QRect(140, 92, 170, 16))
        self.label_battery_state_text = QLabel(self.groupBox_2)
        self.label_battery_state_text.setObjectName(u"label_battery_state_text")
        self.label_battery_state_text.setGeometry(QRect(140, 122, 170, 16))
        self.label_free_storage_text = QLabel(self.groupBox_2)
        self.label_free_storage_text.setObjectName(u"label_free_storage_text")
        self.label_free_storage_text.setGeometry(QRect(140, 152, 170, 16))
        self.label_storage_level_text = QLabel(self.groupBox_2)
        self.label_storage_level_text.setObjectName(u"label_storage_level_text")
        self.label_storage_level_text.setGeometry(QRect(140, 182, 170, 16))
        self.table_scenario_contents = QTableView(self.centralwidget)
        self.table_scenario_contents.setObjectName(u"table_scenario_contents")
        self.table_scenario_contents.setGeometry(QRect(10, 860, 1461, 791))
        self.table_scenario_contents.setAlternatingRowColors(False)
        self.table_scenario_contents.setSelectionMode(QAbstractItemView.SingleSelection)
        self.table_scenario_contents.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table_scenario_contents.horizontalHeader().setStretchLastSection(True)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 840, 355, 15))
        self.btn_scenario_reload = QPushButton(self.centralwidget)
        self.btn_scenario_reload.setObjectName(u"btn_scenario_reload")
        self.btn_scenario_reload.setGeometry(QRect(140, 1650, 71, 41))
        self.btn_scenario_save = QPushButton(self.centralwidget)
        self.btn_scenario_save.setObjectName(u"btn_scenario_save")
        self.btn_scenario_save.setGeometry(QRect(10, 1650, 121, 41))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(1600, 1360, 341, 101))
        self.btn_scenario_run = QPushButton(self.groupBox_3)
        self.btn_scenario_run.setObjectName(u"btn_scenario_run")
        self.btn_scenario_run.setEnabled(True)
        self.btn_scenario_run.setGeometry(QRect(10, 30, 100, 61))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scenario_run.sizePolicy().hasHeightForWidth())
        self.btn_scenario_run.setSizePolicy(sizePolicy)
        self.btn_scenario_run.setAutoFillBackground(False)
        self.btn_scenario_run.setStyleSheet(u"background-color: rgb(170, 121, 66);")
        icon = QIcon()
        icon.addFile(u"../../.designer/flame-avsim-manager/ico/play_circle.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_scenario_run.setIcon(icon)
        self.btn_scenario_run.setIconSize(QSize(32, 32))
        self.btn_scenario_run.setFlat(False)
        self.btn_scenario_stop = QPushButton(self.groupBox_3)
        self.btn_scenario_stop.setObjectName(u"btn_scenario_stop")
        self.btn_scenario_stop.setGeometry(QRect(120, 30, 100, 61))
        self.btn_scenario_stop.setStyleSheet(u"background-color: rgb(170, 121, 66);")
        icon1 = QIcon()
        icon1.addFile(u"../../.designer/flame-avsim-manager/ico/stop_circle.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_scenario_stop.setIcon(icon1)
        self.btn_scenario_stop.setIconSize(QSize(32, 32))
        self.btn_scenario_pause = QPushButton(self.groupBox_3)
        self.btn_scenario_pause.setObjectName(u"btn_scenario_pause")
        self.btn_scenario_pause.setGeometry(QRect(230, 30, 100, 61))
        self.btn_scenario_pause.setStyleSheet(u"background-color: rgb(170, 121, 66);")
        icon2 = QIcon()
        icon2.addFile(u"../../.designer/flame-avsim-manager/ico/pause_circle.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_scenario_pause.setIcon(icon2)
        self.btn_scenario_pause.setIconSize(QSize(32, 32))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(1490, 860, 561, 271))
        self.table_coapp_status = QTableView(self.groupBox_4)
        self.table_coapp_status.setObjectName(u"table_coapp_status")
        self.table_coapp_status.setGeometry(QRect(10, 30, 541, 231))
        self.table_coapp_status.setAlternatingRowColors(False)
        self.table_coapp_status.horizontalHeader().setStretchLastSection(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1320, 10, 101, 16))
        self.table_sound_files = QTableView(self.centralwidget)
        self.table_sound_files.setObjectName(u"table_sound_files")
        self.table_sound_files.setEnabled(True)
        self.table_sound_files.setGeometry(QRect(1320, 30, 251, 711))
        self.table_sound_files.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_sound_files.horizontalHeader().setStretchLastSection(True)
        self.btn_resume = QPushButton(self.centralwidget)
        self.btn_resume.setObjectName(u"btn_resume")
        self.btn_resume.setGeometry(QRect(1560, 750, 80, 80))
        self.btn_play = QPushButton(self.centralwidget)
        self.btn_play.setObjectName(u"btn_play")
        self.btn_play.setGeometry(QRect(1290, 750, 80, 80))
        self.btn_stop = QPushButton(self.centralwidget)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setGeometry(QRect(1380, 750, 80, 80))
        self.btn_pause = QPushButton(self.centralwidget)
        self.btn_pause.setObjectName(u"btn_pause")
        self.btn_pause.setGeometry(QRect(1470, 750, 80, 80))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(1580, 620, 351, 111))
        self.chk_fade_out = QCheckBox(self.groupBox_5)
        self.chk_fade_out.setObjectName(u"chk_fade_out")
        self.chk_fade_out.setGeometry(QRect(10, 30, 131, 20))
        self.chk_fade_in = QCheckBox(self.groupBox_5)
        self.chk_fade_in.setObjectName(u"chk_fade_in")
        self.chk_fade_in.setGeometry(QRect(10, 50, 131, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 2080, 22))
        self.menuCapture = QMenu(self.menubar)
        self.menuCapture.setObjectName(u"menuCapture")
        self.menuCapture_Image_after_time_delay_png = QMenu(self.menuCapture)
        self.menuCapture_Image_after_time_delay_png.setObjectName(u"menuCapture_Image_after_time_delay_png")
        self.menuProcess = QMenu(self.menubar)
        self.menuProcess.setObjectName(u"menuProcess")
        self.menuHPE_model = QMenu(self.menuProcess)
        self.menuHPE_model.setObjectName(u"menuHPE_model")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuCapture.menuAction())
        self.menubar.addAction(self.menuProcess.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menuCapture.addSeparator()
        self.menuCapture.addAction(self.actionCapture_img_png)
        self.menuCapture.addAction(self.actionCapture_Image_with_Keypoints_png)
        self.menuCapture.addAction(self.menuCapture_Image_after_time_delay_png.menuAction())
        self.menuCapture.addAction(self.actionconnect_All)
        self.menuCapture_Image_after_time_delay_png.addAction(self.action_capture_after_20s)
        self.menuCapture_Image_after_time_delay_png.addAction(self.action_capture_after_10s)
        self.menuCapture_Image_after_time_delay_png.addAction(self.action_capture_after_30s)
        self.menuProcess.addSeparator()
        self.menuProcess.addAction(self.menuHPE_model.menuAction())
        self.menuProcess.addAction(self.actionShow_Keypoints)
        self.menuHPE_model.addAction(self.actionYOLO)
        self.menuHPE_model.addAction(self.actionYOLOv2)
        self.menuHPE_model.addAction(self.actionYOLOv3)
        self.menuHPE_model.addAction(self.actionYOLOv4)
        self.menuHPE_model.addAction(self.actionYOLOv8x_pose)
        self.menuFile.addAction(self.actionOpen_operating_scenario)
        self.menuFile.addAction(self.actionLoad_sound_files)
        self.menuFile.addAction(self.actionExit)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionCapture_img_png.setText(QCoreApplication.translate("MainWindow", u"Capture image(*.png)", None))
        self.actionYOLOv8n_pose.setText(QCoreApplication.translate("MainWindow", u"YOLOv8n-pose", None))
        self.actionYOLO.setText(QCoreApplication.translate("MainWindow", u"YOLOv8n-pose", None))
        self.actionYOLOv2.setText(QCoreApplication.translate("MainWindow", u"YOLOv8s-pose", None))
        self.actionYOLOv3.setText(QCoreApplication.translate("MainWindow", u"YOLOv8m-pose", None))
        self.actionYOLOv4.setText(QCoreApplication.translate("MainWindow", u"YOLOv8l-pose", None))
        self.actionYOLOv8x_pose.setText(QCoreApplication.translate("MainWindow", u"YOLOv8x-pose", None))
        self.actionOpen_operating_scenario.setText(QCoreApplication.translate("MainWindow", u"Open operating scenario", None))
        self.actionLoad_sound_files.setText(QCoreApplication.translate("MainWindow", u"Load sound files...", None))
        self.actionShow_Keypoints.setText(QCoreApplication.translate("MainWindow", u"Show Keypoints", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.action_capture_after_30s.setText(QCoreApplication.translate("MainWindow", u"30s", None))
        self.actionconnect_All.setText(QCoreApplication.translate("MainWindow", u"connect All", None))
        self.actionCapture_Image_with_Keypoints_png.setText(QCoreApplication.translate("MainWindow", u"Capture Image with Keypoints(*.png)", None))
        self.action_capture_after_20s.setText(QCoreApplication.translate("MainWindow", u"10s", None))
        self.action_capture_after_10s.setText(QCoreApplication.translate("MainWindow", u"20s", None))
        self.window_camera_2.setText(QCoreApplication.translate("MainWindow", u"Camera #2", None))
        self.window_camera_1.setText(QCoreApplication.translate("MainWindow", u"Camera #1", None))
        self.window_camera_4.setText(QCoreApplication.translate("MainWindow", u"Camera #4", None))
        self.window_camera_3.setText(QCoreApplication.translate("MainWindow", u"Camera #3", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"System Status", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"GPU-0 Usage", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"GPU-0 Mem. Usage", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Glass Device Info.", None))
        self.label_ip.setText(QCoreApplication.translate("MainWindow", u"IP :", None))
        self.label_name.setText(QCoreApplication.translate("MainWindow", u"Name :", None))
        self.label_battery_level.setText(QCoreApplication.translate("MainWindow", u"Battery Level :", None))
        self.label_free_storage.setText(QCoreApplication.translate("MainWindow", u"Free Storage :", None))
        self.label_battery_state.setText(QCoreApplication.translate("MainWindow", u"Battery State :", None))
        self.label_storage_level.setText(QCoreApplication.translate("MainWindow", u"Storage Level :", None))
        self.label_ip_text.setText("")
        self.label_name_text.setText("")
        self.label_battery_level_text.setText("")
        self.label_battery_state_text.setText("")
        self.label_free_storage_text.setText("")
        self.label_storage_level_text.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Operating Scenario", None))
        self.btn_scenario_reload.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.btn_scenario_save.setText(QCoreApplication.translate("MainWindow", u"Save && Update", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Scenario Control", None))
        self.btn_scenario_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.btn_scenario_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_scenario_pause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"co-application status", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Sound files", None))
        self.btn_resume.setText(QCoreApplication.translate("MainWindow", u"Resume", None))
        self.btn_play.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.btn_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_pause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Sound Options", None))
        self.chk_fade_out.setText(QCoreApplication.translate("MainWindow", u"Apply Fade Out", None))
        self.chk_fade_in.setText(QCoreApplication.translate("MainWindow", u"Apply Fade In", None))
        self.menuCapture.setTitle(QCoreApplication.translate("MainWindow", u"Capture", None))
        self.menuCapture_Image_after_time_delay_png.setTitle(QCoreApplication.translate("MainWindow", u"Capture Image after time delay(*.png)", None))
        self.menuProcess.setTitle(QCoreApplication.translate("MainWindow", u"Process", None))
        self.menuHPE_model.setTitle(QCoreApplication.translate("MainWindow", u"HPE model", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

